source 'https://rubygems.org'

gem 'rails', '3.2.14'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'



# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

gem "infopark_rails_connector"
gem "infopark_cloud_connector"
group :assets do
  gem "therubyracer", :require => "v8"
end

group :test, :development do
  gem "infopark_kickstarter", :path => "../../../"
end

gem "active_attr"
gem "simple_form"
gem "haml-rails"
gem "cells"
gem "utf8-cleaner"
gem "infopark_crm_connector"
group :assets do
  gem "less-rails-bootstrap", "~> 2.3"
end

group :assets do
  gem "bootstrap-datepicker-rails"
end

group :test, :development do
  gem "pry-rails"
  gem "rails-footnotes"
  gem "thin"
  gem "infopark_dashboard"
end

group :development do
  gem "better_errors"
  gem "binding_of_caller"
end

gem "gravatar_image_tag"
group :test, :development do
  gem "rspec-rails"
end

gem "airbrake"
gem "honeybadger"
gem "newrelic_rpm"
gem "video_info"
gem "projekktor-rails"